task1
olegdavimuka/pb19_web6_task_manager pull request #2
Opened 2024-02-25 11:38 UTC by yulia4pl

Task1 (web6, group 1)

2024-02-26 07:47 UTC, olegdavimuka requested changes

2024-02-26 07:47 UTC, olegdavimuka commented on tasks/storage.py
> +    return [("V" if task["completed"] else "-", i, task["title"]) for i, task in enumerate(_DB)]
Формат виведення має бути [✔️] <index> - <title> для виконаних і [ ] <index> - <title> для невиконаних завдань.

2024-02-29 19:26 UTC, yulia4pl commented on tasks/storage.py
> +    return [("V" if task["completed"] else "-", i, task["title"]) for i, task in enumerate(_DB)]
Виправила, зміни запушила

2024-03-01 14:47 UTC, olegdavimuka approved these changes

2024-09-07 10:48 UTC, closed without merging