Task4
olegdavimuka/pb19_web6_task_manager pull request #4
Opened 2024-02-25 11:39 UTC by yulia4pl

Task4 (web6, group 1)

2024-02-26 07:53 UTC, olegdavimuka requested changes

2024-02-26 07:53 UTC, olegdavimuka commented on tasks/cli.py
> +            try:
доцільно буде винести в окрему функцію, щось типу get_valid_index, так як функціонал повторюється більше ніж в одному місці

2024-02-26 07:53 UTC, olegdavimuka commented on tasks/cli.py
> +    user_input1 = input("\nDo you want to exit (y/n)?")
Аналогічно як і до минулих пул реквестів - зміни не відносяться до цього завдання + у всіх наступних файлах в цьому ПР аналогічна ситуація

2024-02-29 19:25 UTC, yulia4pl commented on tasks/cli.py
> +            try:
Виправила, зміни запушила

2024-03-01 14:52 UTC, olegdavimuka approved these changes

2024-09-07 10:48 UTC, closed without merging